language: ruby

rvm:
  - 2.2
  - 2.1.6
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - ruby-head
  - jruby-9.0.0.0.pre1
  - jruby-1.7.9-d19

env:
  - RSPEC_VERSION=master
  - RSPEC_VERSION='~> 3.0.0'
  - RSPEC_VERSION='~> 2.99.0'
  - RSPEC_VERSION='~> 2.14.0'

# whitelist
branches:
  only:
    - 1-1-2--wsd-must-req-all-rspec-rails

bundler_args: "--retry=3 --jobs=3"

script: "bundle exec rake ci --trace"

matrix:
  allow_failures:
    - rvm: 2.2
    - rvm: ruby-head
    - rvm: jruby-9.0.0.0.pre1
    - rvm: jruby-1.7.9-d19

