language: ruby

before_install:
  - gem install bundler --version '>=1.9.5'  #  so we can be sure to set code of conduct option= false to avoid an interactive prompt
  - bundle --version

rvm:
  - 2.2
  - 2.1.6
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2.1.1
#  - 1.8.7
#  - ruby-head

env:
 - RSPEC_VERSION='~> 3.3.0'
  - RSPEC_VERSION='~> 3.2.0'
  - RSPEC_VERSION='~> 3.1.0'
  - RSPEC_VERSION='~> 3.0.0'
 # - RSPEC_VERSION=master
  - RSPEC_VERSION='~> 2.99.0'
#  - RSPEC_VERSION='~> 2.14.0'

# whitelist
branches:
  only:
    - wsd--example-app-working
    - 1-1-2--wsd-must-req-all-rspec-rails
    - master

bundler_args: "--retry=3 --jobs=3"

script: "bundle exec rake ci --trace"

matrix:
  allow_failures:
    - rvm: 2.2
    - rvm: ruby-head
    - rvm: jruby-9.0.0.0.pre1
    - rvm: jruby-1.7.9-d19

