version: 1.1.3pre-'{build}'

branches:
  only:
  - appveyor-testing

environment:
  matrix:
    - ruby_version: "200-x64"
      RSPECVERSION:  "~> 3.3.0"
    - ruby_version: "200-x64"
      RSPECVERSION:  "~> 3.2.0"

    - ruby_version: "21-x64"
      RSPECVERSION:  "~> 3.0.0"


matrix:
  allow_failures:
    - RSPECVERSION: '~> 2.99.0'


install:
  - echo *********************
  - echo Starting install...
  - echo RSPECVERSION is %RSPECVERSION%.
  - echo Ruby version is %ruby_version%.
  - SET RSPEC_VERSION=%RSPECVERSION%
  - SET PATH=C:\Ruby%ruby_version%\bin;C:\Ruby%ruby_version%\DevKit;C:\%PATH%
  - SET RSPEC_VERSION
  - SET PATH
  - gem install bundler --version "~> 1.9.5" --no-rdoc --no-ri # cannot cache because ruby version changes
  - bundle install
  - gem --version
  - bundler --version
  - ruby --version

build: off

test_script:
  - bundle exec rake ci --trace
