version: 1.1.3pre-'{build}'

branches:
  only:
  - wsd--example-app-working

install:
  - SET RSPEC_VERSION=$(rspec_version)
  - SET PATH=C:\Ruby%ruby_version%\bin;C:\Ruby%ruby_version%\DevKit;C:\%PATH%
  - gem install bundler --version '>=1.9.5'
  - bundle install
  - gem --version
  - bundler --version
  - ruby --version

build: off

before_test:
  - ps: $env:rspec_version

test_script:
  - bundle exec rake ci --trace


environment:
  rspec_version: "~> 3.3.0"
  rspec_version: "~> 3.2.0"
  rspec_version: "~> 3.1.0"
  rspec_version: "~> 3.0.0"
  rspec_version: "~> 2.99.0"

  matrix:
    - ruby_version: "193"
    - ruby_version: "200"
    - ruby_version: "200-x64"
    - ruby_version: "21"
    - ruby_version: "21-x64"
    - ruby_version: "22"
    - ruby_version: "22-x64"


matrix:
  allow_failures:
    - rspec_version: '~> 2.99.0'

