version: 1.1.3pre-'{build}'

branches:
  only:
  - wsd--example-app-working

install:
  - SET RSPEC_VERSION=$(rspec_version)
  - SET PATH=C:\Ruby%ruby_version%\bin;C:\Ruby%ruby_version%\DevKit;C:\%PATH%
  - gem install bundler --version "~> 1.9.5" --no-rdoc --no-ri
  - bundle install
  - gem --version
  - bundler --version
  - ruby --version

build: off

before_test:
  - ps: $env:rspec_version

test_script:
  - bundle exec rake ci --trace

environment:
  matrix:
    - ruby_version: "193"
      rspec_version:  "~> 3.3.0"
    - ruby_version: "193"
      rspec_version:  "~> 3.2.0"
    - ruby_version: "193"
      rspec_version:  "~> 3.1.0"
    - ruby_version: "193"
      rspec_version:  "~> 3.0.0"
    - ruby_version: "193"
      rspec_version:  "~> 2.9.9"


    - ruby_version: "200"
      rspec_version:  "~> 3.3.0"
    - ruby_version: "200"
      rspec_version:  "~> 3.2.0"
    - ruby_version: "200"
      rspec_version:  "~> 3.1.0"
    - ruby_version: "200"
      rspec_version:  "~> 3.0.0"
    - ruby_version: "200"
      rspec_version:  "~> 2.99.0"


    - ruby_version: "200-x64"
      rspec_version:  "~> 3.3.0"
    - ruby_version: "200-x64"
      rspec_version:  "~> 3.2.0"
    - ruby_version: "200-x64"
      rspec_version:  "~> 3.1.0"
    - ruby_version: "200-x64"
      rspec_version:  "~> 3.0.0"
    - ruby_version: "200-x64"
      rspec_version:  "~> 2.99.0"


    - ruby_version: "21"
      rspec_version:  "~> 3.3.0"
    - ruby_version: "21"
      rspec_version:  "~> 3.2.0"
    - ruby_version: "21"
      rspec_version:  "~> 3.1.0"
    - ruby_version: "21"
      rspec_version:  "~> 3.0.0"
    - ruby_version: "21"
      rspec_version:  "~> 2.99.0"


    - ruby_version: "21-x64"
      rspec_version:  "~> 3.3.0"
    - ruby_version: "21-x64"
      rspec_version:  "~> 3.2.0"
    - ruby_version: "21-x64"
      rspec_version:  "~> 3.1.0"
    - ruby_version: "21-x64"
      rspec_version:  "~> 3.0.0"
    - ruby_version: "21-x64"
      rspec_version:  "~> 2.99.0"


    - ruby_version: "22"
      rspec_version:  "~> 3.3.0"
    - ruby_version: "22"
      rspec_version:  "~> 3.2.0"
    - ruby_version: "22"
      rspec_version:  "~> 3.1.0"
    - ruby_version: "22"
      rspec_version:  "~> 3.0.0"
    - ruby_version: "22"
      rspec_version:  "~> 2.99.0"


    - ruby_version: "22-x64"
      rspec_version:  "~> 3.3.0"
    - ruby_version: "22-x64"
      rspec_version:  "~> 3.2.0"
    - ruby_version: "22-x64"
      rspec_version:  "~> 3.1.0"
    - ruby_version: "22-x64"
      rspec_version:  "~> 3.0.0"
    - ruby_version: "22-x64"
      rspec_version:  "~> 2.99.0"



matrix:
  allow_failures:
    - rspec_version: '~> 2.99.0'

